tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG
    before: |
      cd /workspace/AWSDevOpsProjects
      source ./bin/set_tf_alias
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      cd /workspace/AWSDevOpsProjects
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace/AWSDevOpsProjects
      source ./bin/set_tf_alias
      source ./bin/install_aws_cli
      cd /workspace/AWSDevOpsProjects
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform